apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pong-svc
  template:
    metadata:
      labels:
        app: pong-svc
    spec:
      containers:
      - name: pong-svc
        image: pong-svc:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
