apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ping-svc
  template:
    metadata:
      labels:
        app: ping-svc
    spec:
      containers:
      - name: ping-svc
        image: ping-svc:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
